### PR TITLE
Adapting the RPKI Validation to the new single interval format

### PR DESCRIPTION
**Pull request by salsh**
Due to the change of the time window format, the RPKI Validation did not work properly anymore or could not even compile.

@digizeph Be careful, please include the RPKI section in your testsuite to see if changes affect the code.

### CODE REVIEW

**Comment by digizeph** [comment]
@salsh Thanks for the PR, I'll review it soon. In the mean time, could you give me some context on why you want to make the change? Is there some upstream changes that break the current version?
Thanks!

**Comment by digizeph** [comment]
While I'm trying to install the required environment, I had the following error when making `ROAFetchlib`:
```
rpki_config.c: In function ‘cfg_create’:
rpki_config.c:72:46: error: invalid application of ‘sizeof’ to incomplete type ‘struct pfx_table’
   val->pfxt = malloc(MAX_RPKI_COUNT * sizeof(struct pfx_table));
                                              ^
rpki_config.c:74:5: warning: implicit declaration of function ‘pfx_table_init’ [-Wimplicit-function-declaration]
     pfx_table_init(&val->pfxt[i], NULL);
     ^
rpki_config.c:74:5: error: invalid use of undefined type ‘struct pfx_table’
rpki_config.c:74:30: error: dereferencing pointer to incomplete type ‘struct pfx_table’
     pfx_table_init(&val->pfxt[i], NULL);
                              ^
rpki_config.c: In function ‘cfg_destroy’:
rpki_config.c:123:5: warning: implicit declaration of function ‘pfx_table_free’ [-Wimplicit-function-declaration]
     pfx_table_free(&cfg->cfg_val.pfxt[i]);
     ^
rpki_config.c:123:5: error: invalid use of undefined type ‘struct pfx_table’
rpki_config.c: In function ‘cfg_parse_urls’:
rpki_config.c:191:5: warning: implicit declaration of function ‘pfx_table_src_remove’ [-Wimplicit-function-declaration]
     pfx_table_src_remove(&val->pfxt[i], NULL);
     ^
rpki_config.c:191:5: error: invalid use of undefined type ‘struct pfx_table’
rpki_config.c:212:9: error: invalid use of undefined type ‘struct pfx_table’
         if (cfg_import_roa_file(roa_arg, &val->pfxt[val->pfxt_count]) != 0) {
         ^
rpki_config.c:216:9: error: invalid use of undefined type ‘struct pfx_table’
         if (cfg_import_roa_file(roa_arg, &val->pfxt[0]) != 0) {
         ^
rpki_config.c: In function ‘cfg_add_record_to_pfx_table’:
rpki_config.c:358:7: warning: implicit declaration of function ‘pfx_table_add’ [-Wimplicit-function-declaration]
   if (pfx_table_add(pfxt, &pfx) == PFX_ERROR) {
       ^
Makefile:481: recipe for target 'rpki_config.lo' failed
make[4]: *** [rpki_config.lo] Error 1
make[4]: Leaving directory '/home/vagrant/src/ROAFetchlib/src/lib'
Makefile:521: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/vagrant/src/ROAFetchlib/src/lib'
Makefile:567: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vagrant/src/ROAFetchlib/src'
Makefile:407: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/src/ROAFetchlib'
Makefile:339: recipe for target 'all' failed
make: *** [all] Error 2
```
I have added `LD_LIBRARY_PATH` and `CPPFLAGS` for rtrlib. Also tried setting flags for configure.

VM OS Version:
```
vagrant@ubuntu-xenial:~/src/ROAFetchlib$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Comment by salsh** [comment]
What was the output of ```$ ./configure CFLAGS='-L<path_to_librtr.so> -I<path_to_rtrlib_includes>'```? 
The configure should already check whether the RTRlib is passed properly.

Was the installation of the RTRlib successful without any errors? Was it installed globally or locally?

**Comment by alistairking** [comment]
@digizeph it seems that the rtrlib header files include from `rtrlib/lib` so maybe something like this:
(also, -L takes a path, not a file as its argument)
`./configure -L/usr/local/lib/x86_64-linux-gnu/ -I/usr/local/include`

**Comment by digizeph** [comment]
@salsh @alistairking Unfortunately, changing `-L` input to the directory, and using `-I/usr/local/include` doesn't resolve the problem. Same errors as before. 
```
configure:3758: checking whether the C compiler works
configure:3780: gcc -L/usr/local/lib/x86_64-linux-gnu/ -I/usr/local/include/ /usr/local/include/rtrlib  conftest.c  >&5
/usr/bin/ld: cannot find /usr/local/include/rtrlib: File format not recognized
collect2: error: ld returned 1 exit status
```
Yes, I noticed the `-L` option should provide a directory but the documentation says otherwise. I really wish @salsh could  provide a default paths (commands) in the documentation for the ones that just do `sudo make install` for all of their dependent libraries. (Otherwise, users need to look up where the libraries and so are installed)

**Comment by alistairking** [comment]
Somehow you're passing in `/usr/local/include/rtrlib` to some CFLAGS or CPPFLAGS or something. That's what is causing configure to break.

**Comment by digizeph** [comment]
Just re-downloaded the repository, did a `./autobuild.sh` and `./configure`, same error:
```
configure:3758: checking whether the C compiler works
configure:3780: gcc  /usr/local/include/rtrlib  conftest.c  >&5
/usr/bin/ld: cannot find /usr/local/include/rtrlib: File format not recognized
collect2: error: ld returned 1 exit status
```
I think @alistairking is right about the extract `/usr/local/include/rtrlib` added to the configure.

**Comment by digizeph** [comment]
@salsh My mistake. I added the `/usr/local/include/rtrlib` in my bash environment, causing the configuration trouble. After removing it, the configure can now pass without a problem, and I'm back to the `make` problem.
https://github.com/CAIDA/libbgpstream/pull/58#issuecomment-431927193

I have updated the `config.log` gist: https://gist.github.com/digizeph/2d7aaa5e58c56b874f097ea890f5fcce

**Comment by salsh** [comment]
Hm looks like the configuration is getting the includes directly but the make process doesn't. I think the CPPFLAGS should do the trick (without the rtrlib at the end):
```$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu/```
```$ export CPPFLAGS=$CPPFLAGS"-I/usr/local/include"```
```$ ./configure CFLAGS="-L/usr/local/lib/x86_64-linux-gnu/ -I/usr/local/include"```

**Comment by digizeph** [comment]
@salsh unfortunately, that doesn't solve the problem. Without exporting the flags, the gcc already taks the correct input. Here is the output from `make`:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../src/lib/utils -I../../src/lib/jsmn -L/usr/local/lib/x86_64-linux-gnu/ -I/usr/local/include/ -MT rpki_config.lo -MD -MP -MF .deps/rpki_config.Tpo -c rpki_config.c  -fPIC -DPIC -o .libs/rpki_config.o
rpki_config.c: In function ‘cfg_create’:
rpki_config.c:72:46: error: invalid application of ‘sizeof’ to incomplete type ‘struct pfx_table’
   val->pfxt = malloc(MAX_RPKI_COUNT * sizeof(struct pfx_table));
```

It already has the library and include paths in it.

**Comment by salsh** [comment]
I was able to reproduce the error. The reason for the error is the new release of the RTRlib. Sorry for the inconvenience. Please use the 0.5 release.

**Comment by digizeph** [comment]
@salsh no worries! I'll use 0.5 release for testing this PR and get back to you soon.

**Comment by salsh** [comment]
Okay, thank you! I'll hopefully have it fixed in the very near future.

**Comment by salsh** [comment]
Now it should work with the latest release of the RTRlib.

**Comment by digizeph** [comment]
@salsh Cool. I'll try it out soon.

**Comment by digizeph** [comment]
@salsh everything works now. The PR looks good to me. I'll merge it now. Thank you for your contribution!

**Comment by digizeph** [comment]
@salsh forgot to mention, I used the master branch of RTRLib instead of the release. apparently, there is no new release for the changes you made at the time when I tried to test it.

**Pull request merged**
