### PR TITLE
Fix HTTPS download failures caused by creating too many concurrent HTTPS sessions

### PR DESCRIPTION
**Pull request by salcock**
When opening multiple overlapping groups, it was possible to have in excess of 60 concurrent HTTPS handshakes being attempted to data.ris.ripe.net. This appeared to trigger some sort of DoS protection and all of the connections would be abruptly dropped. This would appear to the user as a failure to open update and RIB files when using either bgpstream or pybgpstream.

With this change, when opening a group, we force an "open wait" call (i.e. block until the element is opened successfully) every 15 elements, which seems to be enough to allow the HTTPS connections to succeed and bgpstream programs to behave as expected.

This change will obviously introduce a little bit of extra delay when opening a batch of resources, but in theory it should not be noticeable.

### CODE REVIEW

**Comment by dacCR** [comment]
I thought this update was to fix pybgpstream to be able to handle http to https redirections. 
We've not been able to use this since we found this problem. Seems this will not be approved so how are others getting past this problem?

`1707143786 HTTP ERROR: SSL connect error (35)
2024-02-05 14:36:26 202247: bs_transport_file.c:39: ERROR: Could not open http://data.ris.ripe.net/rrc04/2024.01/updates.20240109.1430.gz for reading
2024-02-05 14:36:26 202247: bgpstream_transport.c:97: ERROR: Could not open resource (http://data.ris.ripe.net/rrc04/2024.01/updates.20240109.1430.gz)
2024-02-05 14:36:26 202247: bgpstream_reader.c:169: WARNING: Could not open (http://data.ris.ripe.net/rrc04/2024.01/updates.20240109.1430.gz). Attempt 1 of 5
`

**Review by brendonj — APPROVED** [review]
Looks good to me. Got a couple more ducks to line up and then we'll get new packages built.

**Comment by dac2020** [comment]
Should this be working now or am I missing something?

`
# pip install -r requirements.txt --upgrade
Requirement already satisfied: attrs==21.2.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (21.2.                                            0)
Requirement already satisfied: Automat==20.2.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (20.                                            2.0)
Requirement already satisfied: Babel==2.8.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: bcrypt==3.2.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (3.2.0                                            )
Requirement already satisfied: blinker==1.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.4)
Requirement already satisfied: certifi==2020.6.20 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (                                            2020.6.20)
Requirement already satisfied: chardet==4.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (4.0.                                            0)
Requirement already satisfied: click==8.0.3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 8)) (8.0.3)
ERROR: Could not find a version that satisfies the requirement cloud-init==23.1.2 (from versions: none)
ERROR: No matching distribution found for cloud-init==23.1.2

# pip install --upgrade pybgpstream
Requirement already satisfied: pybgpstream in /usr/local/lib/python3.10/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from pybgpstream) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->pybgpstream) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
`

**Comment by brendonj** [comment]
That looks like `cloud-init` is missing, and not installable by pip:

```
ERROR: Could not find a version that satisfies the requirement cloud-init==23.1.2 (from versions: none)
ERROR: No matching distribution found for cloud-init==23.1.2
```

Can you verify that it exists by searching https://pypi.org/search/, and that the name/version are correct? It's not a package that I'm familiar with, and not related to bgpstream. It's a separate issue with your python requirements.txt.

The bgpstream related packages appear to be installed ok (though installing through pip rather than apt gives slightly older versions).

**Comment by dac2020** [comment]
Re-instaling using apt-get did the job. 
Thank you for fixing this. Back to learning more about it now.

**Pull request merged**
