### PR TITLE
Add support for skipping BGP messages for ris-live

### PR DESCRIPTION
**Pull request by digizeph**
added the following two statuses for skipped messages and records:
- `BGPSTREAM_FORMAT_SKIPPED_MSG`
- `BGPSTREAM_RECORD_STATUS_SKIPPED_RECORD`

during processing, the skipped messsages are treated similarly as
supported message (still fill the buffer and continue reading), but
without outputing warnings.

Updated the tests for ris-live accordingly. All tests passed.

### CODE REVIEW

**Comment by alistairking** [comment]
It's been a while since I thought about this code, so I'm likely forgetting something, but what would be the downside to just treating these as "unsupported" instead of adding a new "skipped" type?

**Comment by digizeph** [comment]
> It's been a while since I thought about this code, so I'm likely forgetting something, but what would be the downside to just treating these as "unsupported" instead of adding a new "skipped" type?

I have hesitation of using unsupported status for skipped messages because user may lose the ability to differentiate truly unsupported/unexpected message types from the messages types that we intentionally skipped. Other than that, there is no significant reason for adding the status. 

I am fine with not adding these statuses and stay away from altering the core of bgpstream. In this case, I'd like suppress warning messages for the skipped messages.

**Comment by alistairking** [comment]
I get it, but another way of looking at it is that we don't yet support these messages. There's no reason that libbgpstream couldn't one day expose information about OPEN and/or NOTIFICATION messages.

What are the warnings you would see if you used UNSUPPORTED?

**Comment by digizeph** [comment]
> I get it, but another way of looking at it is that we don't yet support these messages. There's no reason that libbgpstream couldn't one day expose information about OPEN and/or NOTIFICATION messages.

This makes sense.

> What are the warnings you would see if you used UNSUPPORTED?

`Unsupported RIS Live message:` + the entire message string.
https://github.com/CAIDA/libbgpstream/blob/74310ad17679a273f1987b254defdc818cd63af2/lib/formats/bs_format_rislive.c#L301

If you think these messages fine to have for OPEN, NOTIFICATION, and KEEPALIVE, I can revert back to use UNSUPPORTED for these messages without further changes.

**Comment by alistairking** [comment]
Oh, gotcha. I thought you mean there was some bgpstream core warning.
I agree, let's just drop that log message from the ris live format.

**Comment by digizeph** [comment]
> Oh, gotcha. I thought you mean there was some bgpstream core warning.
> I agree, let's just drop that log message from the ris live format.

@alistairking this PR is now cleaned up, ready for review now.

**Pull request merged**
