### PR TITLE
Fix broker debug Kafka topic output issue

### PR DESCRIPTION
**Pull request by digizeph**
bgpstream_resource_set_attr calls `strdup` to duplicate the passed in
variable, thus the kafka_topic is fine to be freed after the call.

this resolves the issue where during broker debug the resources
after bmp (which uses kafka) all have the `Kafka topic` output.

### CODE REVIEW

**Comment by alistairking** [comment]
I think you might also need to set `kafka_topic = NULL` after the `free`

**Comment by digizeph** [comment]
> I think you might also need to set `kafka_topic = NULL` after the `free`

Fixed 9b4f9aa. Tested locally with `./tools/bgpreader -w'2020-04-16' -t updates -c rrc00`
```
mingwei@hammer01:~/git/caida-git/libbgpstream$ ./tools/bgpreader -w'2020-04-16' -t updates -c rrc00
2020-04-29 12:48:41 50017: bsdi_broker.c:961: INFO: Query URL: "https://broker.bgpstream.caida.org/v2/data?collectors[]=rrc00&types[]=updates&intervals[]=1586995200,0"
2020-04-29 12:48:41 50017: bsdi_broker.c:450: INFO: ----------
2020-04-29 12:48:41 50017: bsdi_broker.c:451: INFO: Transport Type: 1
2020-04-29 12:48:41 50017: bsdi_broker.c:452: INFO: Format Type: 1
2020-04-29 12:48:41 50017: bsdi_broker.c:453: INFO: URL: bmp.bgpstream.caida.org
2020-04-29 12:48:41 50017: bsdi_broker.c:454: INFO: Project: caida-bmp
2020-04-29 12:48:41 50017: bsdi_broker.c:455: INFO: Collector:
2020-04-29 12:48:41 50017: bsdi_broker.c:456: INFO: Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:457: INFO: InitialTime: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:458: INFO: Duration: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:460: INFO: Kafka topic: ^openbmp\.router--.+\.peer-as--.+\.bmp_raw
2020-04-29 12:48:41 50017: bsdi_broker.c:450: INFO: ----------
2020-04-29 12:48:41 50017: bsdi_broker.c:451: INFO: Transport Type: 3
2020-04-29 12:48:41 50017: bsdi_broker.c:452: INFO: Format Type: 2
2020-04-29 12:48:41 50017: bsdi_broker.c:453: INFO: URL: https://ris-live.ripe.net/v1/stream/?format=json&client=bgpstream-broker
2020-04-29 12:48:41 50017: bsdi_broker.c:454: INFO: Project: ris-live
2020-04-29 12:48:41 50017: bsdi_broker.c:455: INFO: Collector:
2020-04-29 12:48:41 50017: bsdi_broker.c:456: INFO: Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:457: INFO: InitialTime: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:458: INFO: Duration: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:450: INFO: ----------
2020-04-29 12:48:41 50017: bsdi_broker.c:451: INFO: Transport Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:452: INFO: Format Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:453: INFO: URL: http://bgp-archive.caida.org/ris/rrc00/updates/2020/04/15/ris.rrc00.updates.1586994900.gz
2020-04-29 12:48:41 50017: bsdi_broker.c:454: INFO: Project: ris
2020-04-29 12:48:41 50017: bsdi_broker.c:455: INFO: Collector: rrc00
2020-04-29 12:48:41 50017: bsdi_broker.c:456: INFO: Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:457: INFO: InitialTime: 1586994900
2020-04-29 12:48:41 50017: bsdi_broker.c:458: INFO: Duration: 300
2020-04-29 12:48:41 50017: bsdi_broker.c:450: INFO: ----------
2020-04-29 12:48:41 50017: bsdi_broker.c:451: INFO: Transport Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:452: INFO: Format Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:453: INFO: URL: http://bgp-archive.caida.org/ris/rrc00/updates/2020/04/16/ris.rrc00.updates.1586995200.gz
2020-04-29 12:48:41 50017: bsdi_broker.c:454: INFO: Project: ris
2020-04-29 12:48:41 50017: bsdi_broker.c:455: INFO: Collector: rrc00
2020-04-29 12:48:41 50017: bsdi_broker.c:456: INFO: Type: 0
2020-04-29 12:48:41 50017: bsdi_broker.c:457: INFO: InitialTime: 1586995200
2020-04-29 12:48:41 50017: bsdi_broker.c:458: INFO: Duration: 300
......
```

**Comment by alistairking** [comment]
I checked a little more closely and the current code assumes that we reuse the kafka_topic memory to avoid allocating with each resource we process (see https://github.com/CAIDA/libbgpstream/blob/f0983faa24904e656d2d9c9db1e979701b796085/lib/datainterfaces/bsdi_broker.c#L424).

I think this is overkill anyway, but the change you're suggesting here will actually break it because the code assumes that `kafka_topic` points to `topic_len` bytes of memory.
I think we should remove topic_len, and change the realloc to a simple malloc (probably with an assert NULL prior).
Thoughts?

**Comment by digizeph** [comment]
Another idea:
Revert the previous changes and apply the following patch:
```diff
@@ -456,9 +456,14 @@ static int process_json(bsdi_t *di, const char *js, jsmntok_t *root_tok,
           bgpstream_log(BGPSTREAM_LOG_INFO, "Type: %d", type);
           bgpstream_log(BGPSTREAM_LOG_INFO, "InitialTime: %lu", initial_time);
           bgpstream_log(BGPSTREAM_LOG_INFO, "Duration: %lu", duration);
-          if(kafka_topic != NULL){
-            bgpstream_log(BGPSTREAM_LOG_INFO, "Kafka topic: %s", kafka_topic);
+#ifdef WITH_KAFKA
+          if (transport_type == BGPSTREAM_RESOURCE_TRANSPORT_KAFKA) {
+            if(kafka_topic != NULL){
+              bgpstream_log(BGPSTREAM_LOG_INFO, "Kafka topic: %s", kafka_topic);
+            }
           }
+#endif
 #endif
           if (url_set == 0 || project_set == 0 || collector_set == 0 ||
               type_set == 0 || initial_time_set == 0 || duration_set == 0 ||
```

**Comment by alistairking** [comment]
Yep, works for me.
But can we do `if (A && B)` instead of `if (A) if (B)`?

**Pull request closed without merging**
